version: '2'
services:
  nginx:
    image: nginx:alpine
    container_name: farmacia_nginx
    ports:
      - "80:8000"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - static-data:/staticfiles
      - media-data:/mediafiles
    depends_on:
      - web

  web:
    build: .
    container_name: farmacia_app
    command: bash -c "python manage.py migrate && python manage.py collectstatic --no-input && gunicorn thefarmacustomer.wsgi:application -b 0.0.0.0:8000  --workers 3 --log-level=debug"
    volumes:
      - static-data:/thefarmaclient/staticfiles
      - media-data:/thefarmaclient/media
    expose:
      - "8000"
    environment:
     - DEBUG=False
     - API_URL=https://api.thefarma.com.br
     - WS_URL=ws://sock.thefarma.com.br/farmacias/{id_farmacia}/?Authorization:Token {token_representante}

volumes:
  static-data:
  media-data:
