version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: farmacia_nginx
    ports:
      - "80:8000"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - static-data:/staticfiles
      - media-data:/mediafiles
    depends_on:
      - web
    restart: always

  web:
    build: .
    container_name: farmacia_app
    command: bash -c "python manage.py migrate && python manage.py collectstatic --no-input && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/thefarmaclient/
    expose:
      - "8000"
    environment:
     - DEBUG=True
     - API_URL=https://api.thefarma.com.br
     - WS_URL=wss://api.thefarma.com.br/websocket/farmacias/{id_farmacia}/?Authorization:Token {token_representante}
    restart: always

volumes:
  static-data:
  media-data:
